carrerlama/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('^social-auth/', include('social_django.urls', namespace='social')),
    url(r'^admin/', admin.site.urls),
    # url(r'^old/', include('home.urls',namespace='home')),
    url(r'^', include('dashboard.urls', namespace='dashboard')),




]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = ("Career Lama")
admin.site.site_title = ("Career Lama")

dashboard/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views



urlpatterns = [
    url(r'^$',views.index,name='index'),

    url(r'write-a-review/$',views.writeAReview,name='writeAReview'),
    url(r'submit-phase-one/$', views.submitPhaseOne, name='submitPhaseOne'),
    url(r'write-review/(?P<pk>[0-9a-z-]+)/$',views.writeReviewRest,name='writeReviewRest'),
    url(r'submit-phase-two/$',views.submitPhaseTwo,name='submitPhaseTwo'),
    url(r'thanks/$',views.thanks_page,name='thanks_page'),


    url(r'company/(?P<pk>[0-9a-z-]+)/$',views.company,name='company'),


    url(r'login/$',views.login,name='login'),
    url(r'login-check/$',views.login_check,name='login_check'),

    url(r'logout/$',views.logoutUser,name='logoutUser'),

    url(r'register/$',views.register,name='register'),
    url(r'register-me/$',views.register_me,name='register_me'),

    url(r'update-user-profile/$', views.update_user_profile, name='update_user_profile'),
    # url(r'update-user-image/$',views.updateUserImage,name='updateUserImage'),
    url(r'user-profile/$',views.profile,name='profile'),



    url(r'get-all-companies/$',views.get_all_companies,name='get_all_companies'),
    url(r'write-sub-process/$',views.writeSubProcess,name='writeSubProcess'),
    url(r'delete-sub-process/$',views.deleteSubProcess,name='deleteSubProcess'),


    url(r'make-helpful/(?P<pk>[0-9a-z-]+)/$',views.make_helpful,name='helpful'),



    url(r'all-companies/$',views.all_list_companies,name='all_list_companies'),


]

home/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views



urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'all-companies/$',views.allcompanies,name='allcompanies'),

    url(r'all-companies-category/(?P<pk>[0-9a-z-]+)/$',views.category_wise,name='category_wise'),
    url(r'all-companies-location/(?P<pk>[0-9a-z-]+)/$',views.location_wise,name='location_wise'),

    url(r'company/(?P<pk>[0-9a-z-]+)/$',views.company,name='company'),


    url(r'write-review/(?P<pk>[0-9a-z-]+)/$',views.write_review,name='write_review'),

    url(r'submit-review/$',views.submit_review,name='submit_review'),

    url(r'contact/$',views.contact,name='contact'),


    url(r'terms-conditions/$',views.term_condition,name='term_condition'),



]

templates/base.html
{% load staticfiles %}
{% block header %}
<!DOCTYPE html>
<html lang="en">

<head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Carrer Lama</title>

        <!-- Bootstrap -->
        <link href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- Flexslider Css -->
	<link href="{% static 'assets/plugins/flexslider/flexslider.css' %}" rel="stylesheet">
        <!--font awesome-->
        <link href="{% static 'assets/plugins/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
        <!--custom css-->
        <link href="{% static 'assets/plugins/themify/themify-icons.css' %}" rel="stylesheet">
        <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
        <link href="{% static 'assets/css/responsive.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="header-stricky">
            <div class="container">
                <div class="row">
                    <div class="col-md-2">
                        <div class="site-logo">
                            <a href="/"><img src="{% static 'assets/images/carrer-lama-logo.png' %}" alt="" class="img-responsive" style="height:50px;" /></a>
                        </div>
                    </div>
                    <div class="col-md-8">
                      <nav class="navbar navbar-default navbar-static-top">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                            </div>
                            <div id="navbar" class="navbar-collapse collapse">
                                <ul class="nav navbar-nav scrollto">
                                    <li><a href="{% url 'home:allcompanies' %}">Company Reviews</a></li>
                                   <li><a href="">Interviews</a></li>
                                   <li><a href="{% url 'home:allcompanies' %}">Companies</a></li>
                                   <li><a href="">Salary Calculator</a></li>
                                   <li><a href="">Practice Tests</a></li>
                                   <li><a href="">Blog</a> </li>


                                </ul>
                            </div>
                        </nav>
                    </div>
                            <div class="col-md-2 text-right">
                                <a href="{% url 'home:contact' %}" class="login active">Contact us</a>

                            </div>
                        </div>
                    </div>
                </div>


        {% endblock header %}



      {% block content %}

        {% endblock content %}





        {% block footer %}
                <footer id="footer">
                    <div class="container">
                        <div class="row">
                            <div class="footer-block">
                                <h5>Information</h5>
                                <hr>
                                <ul class="footer-link">
                                    <li><a href="">About Us</a></li>
                                    <li><a href="{% url 'home:term_condition' %}">Terms & Conditions</a></li>

                                </ul>
                            </div>

                                <div class="footer-block">
                                <h5>Links</h5>
                                <hr>
                                <ul class="footer-link">
                                    <li><a href="{% url 'home:allcompanies' %}">Company Reviews</a></li>
                                    <li><a href="#">Interviews</a></li>
                                    <li><a href="#">Companies</a></li>

                                    <li><a href="#">Salary Calculator</a></li>
                                    <li><a href="#">Practice Tests</a></li>
                                   <li><a href="">Blog</a> </li>
                                </ul>
                            </div>
                               <div class="footer-block">
                                <h5>Reviews</h5>
                                <hr>
                                <ul class="footer-link">
                                    <li><a href="#">Browse by Companies</a></li>
                                    <li><a href="#">Browse by Designation</a></li>
                                    <li><a href="#">Browse by Location</a></li>

                                </ul>
                            </div>
                            <div class="footer-block">
                                <h5>Reviews</h5>
                                <hr>
                                <ul class="footer-link">
                                    <li><a href="#">Browse by Companies</a></li>
                                    <li><a href="#">Browse by Designation</a></li>
                                    <li><a href="#">Browse by Location</a></li>

                                </ul>
                            </div>
                            <div class="footer-block footer-block2">
                                <h5>Follow Us</h5>
                                <hr>
                                <ul class="follow">
                                    <li><a href="#" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                                    <li><a href="#" title="Google"><span class="ti-google"></span></a></li>
                                    <li><a href="#" title="RSS"><i class="fa fa-rss"></i></a></li>
                                </ul>
                                <div class="border"></div>
                                <div class="register">
                                    <a>{{allcompaniesCount}} <span>Registerd Companies</span></a>
                                </div>
                                <div class="register job">
                                    <a>{{allreviewsCount}} <span>Reviews</span></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="footer-bottom">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-6 col-sm-6 padding-left">
                                    <span>&#169; 2017 Carrerlama. All rights reserved.</span>
                                </div>
                                <div class="col-md-6 col-sm-6 text-right padding-left">
                                    <!--<ul class="bottom_link">-->
                                        <!--<li><a href="#">Link 1</a></li>-->
                                        <!--<li><a href="#">Link 1</a></li>-->
                                        <!--<li><a href="#">Link 1</a></li>-->
                                    <!--</ul>-->
                                </div>
                            </div>
                        </div>
                    </div>
                </footer>
                <!-- jQuery -->
                <script src="{% static 'assets/js/jquery.min.js' %}"></script>
                <script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
                <script src="{% static 'assets/plugins/flexslider/jquery.flexslider-min.js' %}"></script>
                <script src="{% static 'assets/js/jquery.counterup.min.js' %}"></script>
                <script src="{% static 'assets/js/waypoints.min.js' %}"></script>
                <script src="{% static 'assets/js/counter.js' %}"></script>
                <script src="{% static 'assets/js/flexslider.js' %}"></script>
                <script src="{% static 'assets/js/common.js' %}"></script>
                <script src="{% static 'assets/js/bootstrap-rating-input.js' %}"></script>



            </body>
</html>
{% endblock footer %}

templates/base_new.html
{% load staticfiles %}

{% block header %}
<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="UTF-8">
<meta name=viewport content="width=device-width, initial-scale=1.0" />
<meta http-equiv=content-type content="text/html;charset=UTF-8">
<meta http-equiv=X-UA-Compatible content="IE=edge,chrome=1">
<title>Interview Questions | CareerLama</title>


<link rel="stylesheet" href="{% static 'config/css/homepage.css' %}">
<link rel="stylesheet" href="{% static 'config/css/font-awesome.min.css'%} ">
<link rel="stylesheet" href="https://d2vodp2q794hrx.cloudfront.net/fonts/fonticons/style.css">

	{% block extra_css %}

	{% endblock extra_css %}


<!-- end Mixpanel --><!-- Chrome, Firefox OS and Opera -->
<meta name="theme-color" content="#10152E">

<!-- Windows Phone -->
<meta name="msapplication-navbutton-color" content="#10152E">
<!-- iOS Safari -->
<meta name="apple-mobile-web-app-status-bar-style" content="#10152E">
<style>
	.popup {
    width:100%;
    height:100%;
    display:none;
    position:fixed;
    top:0px;
    left:0px;
    background:rgba(0,0,0,0.75);
}

/* Inner */
.popup-inner {
    max-width:280px;
    width:100%;
    padding:40px;
    position:absolute;
    top:50%;
    left:50%;
    -webkit-transform:translate(-50%, -50%);
    transform:translate(-50%, -50%);
    box-shadow:0px 2px 6px rgba(0,0,0,1);
    border-radius:3px;
    background:#fff;
}

/* Close Button */
.popup-close {
    width:30px;
    height:30px;
    padding-top:4px;
    display:inline-block;
    position:absolute;
    top:0px;
    right:0px;
    transition:ease 0.25s all;
    -webkit-transform:translate(50%, -50%);
    transform:translate(50%, -50%);
    border-radius:1000px;
    background:rgba(0,0,0,0.8);
    font-family:Arial, Sans-Serif;
    font-size:20px;
    text-align:center;
    line-height:100%;
    color:#fff;
}

.popup-close:hover {
    -webkit-transform:translate(50%, -50%) rotate(180deg);
    transform:translate(50%, -50%) rotate(180deg);
    background:rgba(0,0,0,1);
    text-decoration:none;
}
</style>

</head>
<body>
<section class="main-menu wow fadeInDown">
	<div class="left-section">
		<a href="/"  taget="_blank">&nbsp;&nbsp;<b>Careerlama</b> </a>


	</div>
	<div class="right-section">

		<a href="{% url 'dashboard:writeAReview' %}" class="highlight" >write a review </a>

		{% if request.user.is_authenticated %}
					<a style="margin-right:-0.5rem;" href="">
						{% if linkedin_profile_url %}
								<img style="border-radius: 50%;" class="usr-thumbnail" src="{{linkedin_profile_url}}"/>
						{% else %}
								{% for val in request.user.social_auth.values_list %}
									<img style="border-radius: 50%;" class="usr-thumbnail" src="https://graph.facebook.com/{{val.4.id}}/picture?type=normal"/>
								{% endfor %}
						{% endif %}

			</a>



			<a href="#" class="js-user-menu">&nbsp; Hi, {{request.user.first_name}} {{request.user.last_name}}</a>
			<div class="user-menu">
				<div class="triangle"></div>
				<a href="{% url 'dashboard:profile' %}"><i class="icon-user"></i> profile</a>
				<a href="{% url 'dashboard:logoutUser' %}"><i class="icon-logout"></i> logout</a>
			</div>
		{% else %}
		{{request.user.username}}


		<a class="btn" data-popup-open="popup-1" href="#">Login</a>

		{% endif %}


<div class="popup" data-popup="popup-1">
    <div class="popup-inner">
		<div align="center">
						<h4 style="color:grey">SIGNUP/LOGIN</h4>
						<h5 style="color:grey">1-Step Login | Get unlimited access!</h5>
		</div>

        <a href="{% url 'social:begin' 'facebook' %}">
			 <img  src="{% static 'config/image/facebook.png' %}"/>
		</a>
		<a href="{% url 'social:begin' 'google-oauth2' %}">
			 <img  src="{% static 'config/image/googl.png' %}"/>
		</a>
		<a href="{% url 'social:begin' 'linkedin-oauth2' %}">
			 <img  src="{% static 'config/image/linkedin.png' %}"/>
		</a>


        <a class="popup-close" data-popup-close="popup-1" href="#">x</a>
    </div>
</div>



			</div>
</section>
<header class="main-header-menu-wrap mobile">
	<div class="main-header-menu">
		<div class="menu js-mobile-menu"><i class="icon-menu-mobile"></i></div>
		<div class="title"><a href="/">CareerLama</a></div>
	</div>
</header>

<header class="main-menu-mobile">
	<div>
		<a href="/" taget="_blank">Home</a>
		<a href="" >Interviews</a>
		<a href="{% url 'dashboard:all_list_companies' %}"  >Companies</a>
		<a href="{% url 'dashboard:writeAReview' %}"  >Write A Review</a>
		<a href="{% url 'dashboard:login' %}"  >Login</a>
	</div>
</header>
<script>
	window.onload=function(){
		$('.js-user-menu').on('click',function(){
			$('.user-menu').fadeToggle(300);
			return false;
		});
		$('.js-mobile-menu').on('click',function(){
			$('.main-menu-mobile').fadeToggle(300);
		});
		$('.main-menu-mobile').not('.main-menu-mobile div').on('click',function(){
			$('.main-menu-mobile').toggle();
		});
		var jsHeadHeight = Math.floor($('.js-menu-shift').height());
		$(window).scroll(function () {
			if(Math.floor($(window).scrollTop()) > jsHeadHeight) {
				$('.main-menu').addClass('solid');
				$('.main-header-menu-wrap').addClass('solid');
			}
			else{
				$('.main-menu').removeClass('solid');
				$('.main-header-menu-wrap').removeClass('solid');
			}
		});


	};




</script>
<script src="{% static 'config/js/jquery-2.2.4.min.js' %}"></script>
{% endblock header %}




{% block content %}

{% endblock content %}




{% block footer %}

<script src="{% static 'config/js/typeahead.bundle.min.js' %}"></script>
<!-- <script src="https://d2vodp2q794hrx.cloudfront.net/js/custom/browse_interviews-1.min.js"></script> -->
<link rel="stylesheet" href="{% static 'config/css/style.css' %}">

<section class="login-popup">
	<div class="login-box">
		<a onclick="loginPopOut()" class="close"><i class="icon-cross"></i></a>

		<div class="right-part">
			<a href="">
				<div style="background-color:#0077B5;"><i class="icon-linkedin"></i></div>
				<div>login with linkedin</div>
			</a>
			<a href="">
				<div style="background-color:#3b5998;"><i class="icon-facebook"></i></div>
				<div>login with facebook</div>
			</a>
			<a href="#" class="customGPlusSignIn" id="customBtn" data-onsuccess="onSignIn" >
				<div style="background-color:#dd4b39;"><i class="icon-google-plus"></i></div>
				<div>login with google</div>
			</a>
		</div>
		<div class="title">
			<div class="headline">SignUp/Login</div>
			<div>1-Step Login | Get unlimited access!</div>
		</div>
		<!--<div class="foot-note">
			*Login is only for verification purpose<br/>
			You can choose to hide your identity later.
		</div>-->
	</div>
</section>
<link rel="stylesheet" href="{% static 'config/css/login-popup.css' %}">
<script src="https://apis.google.com/js/platform.js" async defer></script>

<style type="text/css">

</style>
<link rel="stylesheet" href="{% static 'config/css/more_css.css' %}">
<div class="footer-main-wrap">

	<div class="footer-social-media">
		<div class="line-social"><hr/></div>
		<div id="social-icons">

			{% for link in allSocialLinks %}
				<a href="{{link.social_link}}" target="_blank" ><div id="fb"><i class="{{link.social_link_type}}"></i></div></a>
			{% endfor %}
		</div>
		<div class="line-social"><hr/></div>
	</div>
	<!--<div class="footer-report-issues" >Bugs, Hugs, Suggestions? Ping Us!</div>-->
	<!--<div class="contact-form">-->
		<!--<form method="post" id="contact-us-form">-->
			<!--<input class="email" type="email" name="email" placeholder="Please enter your email" />-->
        	<!--<textarea name="message" id=""  rows="5" placeholder="Type here. "></textarea>-->
        	<!--<input type="submit" value="SUBMIT">-->
		<!--</form>-->


	<!--</div>-->
	<div class="footer-links" style="margin-bottom: 2rem;margin-top: 2rem;">
		<ul>
			<li><a href="">About Us .</a></li>
			<li><a href="">Join us .</a></li>
			<li><a href="{% url 'dashboard:all_list_companies' %}">Company Reviews</a></li>
			<li><a href="{% url 'dashboard:writeAReview' %}">Write a review</a></li>

			<li><a href="">Our Partners .</a></li>
		</ul>
	</div>
	<div class="about-us-footer" style="margin-bottom: 1rem" >
		CareerLama gives you free access to in-depth authentic information about companies story, products & services, office photos, team, office locations, amusing facts, stats, interview questions, interview tips and much more! Our mission is to help you prepare and research exhaustively about any company you set your eyes on. We need your help in this mission. Checkout how you could contribute <a href="/contribute" target="_blank" >here</a>.
		</div>
	<div class="footer-flight-image">

	</div>


	<div class="copyright">&copy; 2017 CareerLama.com. All rights reserved.</div>
	<div class="privacy-policy"><a href="" target="_blank" >Disclaimer</a> &nbsp;|&nbsp; <a href="" target="_blank" >Privacy policy</a></div>
</div>
<div class="footer-main-wrap--mobile">
	<i class="icon-CareerLama"></i>
	<div class="footer-report-issues">Bugs, Hugs, Suggestions? Ping Us!</div>

	<ul>

		<li><a href="{% url 'dashboard:all_list_companies' %}">Browse companies</a></li>
		<li><a href="{% url 'dashboard:writeAReview' %}">Write a review</a></li>
		<li><a href="{% url 'dashboard:all_list_companies' %}">Company Reviews</a></li>

	</ul>

	<a class="white-title" href="" target="_blank" >Disclaimer</a> &nbsp;|&nbsp; <a class="white-title" href="" target="_blank" >Privacy policy</a>
	<div class="copyright">&copy; 2017 CareerLama.com. All rights reserved.</div>

</div>

<script>
	$(function() {
    //----- OPEN
    $('[data-popup-open]').on('click', function(e)  {
        var targeted_popup_class = jQuery(this).attr('data-popup-open');
        $('[data-popup="' + targeted_popup_class + '"]').fadeIn(350);

        e.preventDefault();
    });

    //----- CLOSE
    $('[data-popup-close]').on('click', function(e)  {
        var targeted_popup_class = jQuery(this).attr('data-popup-close');
        $('[data-popup="' + targeted_popup_class + '"]').fadeOut(350);

        e.preventDefault();
    });
});
</script>

</body>
</html>
{% endblock footer %}