carrerlama/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('^social-auth/', include('social_django.urls', namespace='social')),
    url(r'^admin/', admin.site.urls),
    # url(r'^old/', include('home.urls',namespace='home')),
    url(r'^', include('dashboard.urls', namespace='dashboard')),




]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = ("Career Lama")
admin.site.site_title = ("Career Lama")

dashboard/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views



urlpatterns = [
    url(r'^$',views.index,name='index'),

    url(r'write-a-review/$',views.writeAReview,name='writeAReview'),
    url(r'submit-phase-one/$', views.submitPhaseOne, name='submitPhaseOne'),
    url(r'write-review/(?P<pk>[0-9a-z-]+)/$',views.writeReviewRest,name='writeReviewRest'),
    url(r'submit-phase-two/$',views.submitPhaseTwo,name='submitPhaseTwo'),
    url(r'thanks/$',views.thanks_page,name='thanks_page'),


    url(r'company/(?P<pk>[0-9a-z-]+)/$',views.company,name='company'),


    url(r'login/$',views.login,name='login'),
    url(r'login-check/$',views.login_check,name='login_check'),

    url(r'logout/$',views.logoutUser,name='logoutUser'),

    url(r'register/$',views.register,name='register'),
    url(r'register-me/$',views.register_me,name='register_me'),

    url(r'update-user-profile/$', views.update_user_profile, name='update_user_profile'),
    # url(r'update-user-image/$',views.updateUserImage,name='updateUserImage'),
    url(r'user-profile/$',views.profile,name='profile'),



    url(r'get-all-companies/$',views.get_all_companies,name='get_all_companies'),
    url(r'write-sub-process/$',views.writeSubProcess,name='writeSubProcess'),
    url(r'delete-sub-process/$',views.deleteSubProcess,name='deleteSubProcess'),


    url(r'make-helpful/(?P<pk>[0-9a-z-]+)/$',views.make_helpful,name='helpful'),



    url(r'all-companies/$',views.all_list_companies,name='all_list_companies'),


]

home/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views



urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'all-companies/$',views.allcompanies,name='allcompanies'),

    url(r'all-companies-category/(?P<pk>[0-9a-z-]+)/$',views.category_wise,name='category_wise'),
    url(r'all-companies-location/(?P<pk>[0-9a-z-]+)/$',views.location_wise,name='location_wise'),

    url(r'company/(?P<pk>[0-9a-z-]+)/$',views.company,name='company'),


    url(r'write-review/(?P<pk>[0-9a-z-]+)/$',views.write_review,name='write_review'),

    url(r'submit-review/$',views.submit_review,name='submit_review'),

    url(r'contact/$',views.contact,name='contact'),


    url(r'terms-conditions/$',views.term_condition,name='term_condition'),



]

dashboard/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from home.models import *
from django.views.generic import TemplateView
from django.views.generic.edit import FormView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from .models import *
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q
from django.contrib.auth import authenticate, login as login_user, logout as logout_user
from django.contrib.auth.models import User
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
import requests
from django.contrib import messages
# from .forms import *
import json, random




class indexView(TemplateView):
	template_name = "index.html"

	def get_context_data(self, **kwargs):
		context = super(self.__class__, self).get_context_data(**kwargs)
		context['allSocialLinks'] = socialMediaLinks.objects.all()
		try:
			del self.request.session['form_errors']
		except:
			pass


		# MIGRATION LINKEDIN PROFILE DATA
		if self.request.user.is_authenticated():
			if self.request.user.is_superuser:pass
			else:
				try:
					userUpdatedInsta  = userinformation.objects.get(user=self.request.user)
				except:
					socialProvider = self.request.user.social_auth.get().provider
					if socialProvider  == 'linkedin-oauth2':
						access_token = self.request.user.social_auth.get().access_token
						urlToHit = """https://api.linkedin.com/v1/people/~:(picture-url)?oauth2_access_token={0}&format=json""".format(access_token)
						responseContent = requests.get(urlToHit)
						actualContent = json.loads(responseContent.content)
						userUpdatedInsta = userinformation(user=self.request.user)
						userUpdatedInsta.alternateUserprofileurl = actualContent['pictureUrl']
						userUpdatedInsta.save()
					if socialProvider == 'google-oauth2':
						access_token = self.request.user.social_auth.get().access_token
						urlToHit = "https://www.googleapis.com/plus/v1/people/me?access_token={0}".format(access_token)
						responseContent = requests.get(urlToHit)
						actualContent = json.loads(responseContent.content)
						userUpdatedInsta = userinformation(user=self.request.user)
						userUpdatedInsta.alternateUserprofileurl = actualContent['image']['url']
						userUpdatedInsta.save()


		# GET USER PROFILE DATA
		if self.request.user.is_authenticated:
			if self.request.user.is_superuser:pass
			else:
				try:
					socialProvider = self.request.user.social_auth.get().provider
					if socialProvider == 'linkedin-oauth2' or 'google-oauth2':
						userUpdatedInsta = userinformation.objects.get(user=self.request.user)
						context['linkedin_profile_url'] = userUpdatedInsta.alternateUserprofileurl
				except:
					pass





		allcompanies = companies.objects.all()
		allcompanies_list = []
		for comps in allcompanies:
			if int(company_interviews.objects.filter(company=comps).count()) > 0:
				allcompanies_list.append(comps)

		paginator = Paginator(allcompanies_list, 30)

		page = self.request.GET.get('page')
		try:
			allcompanies_list = paginator.page(page)
		except PageNotAnInteger:
			allcompanies_list = paginator.page(1)
		except EmptyPage:
			allcompanies_list = paginator.page(paginator.num_pages)

		comps   = []

		for compo in allcompanies_list:
			mydict = {
				"co":compo,
				"count":int(company_interviews.objects.filter(company=compo).count())
			}
			comps.append(mydict)

		context['companySpoof'] = allcompanies_list
		context['companies'] = comps
		return context


class writeAReviewView(TemplateView):
	template_name = "write_feedback.html"

	@method_decorator(login_required)
	def dispatch(self, request, *args, **kwargs):
		if request.user.is_authenticated:
			if request.user.is_superuser:
				return HttpResponseRedirect(reverse('admin:index'))
		return super(self.__class__, self).dispatch(request, *args, **kwargs)


	def get_context_data(self, **kwargs):
		context = super(self.__class__, self).get_context_data(**kwargs)
		# GET USER PROFILE DATA
		if self.request.user.is_authenticated:
			if self.request.user.is_superuser:pass
			else:
				socialProvider = self.request.user.social_auth.get().provider
				if socialProvider == 'linkedin-oauth2':
					userUpdatedInsta = userinformation.objects.get(user=self.request.user)
					context['linkedin_profile_url'] = userUpdatedInsta.alternateUserprofileurl
				if socialProvider  == 'google-oauth2':
					userUpdatedInsta = userinformation.objects.get(user=self.request.user)
					context['linkedin_profile_url'] = userUpdatedInsta.alternateUserprofileurl



		context['allSocialLinks'] = socialMediaLinks.objects.all()
		allcompanies = companies.objects.all().order_by('company_name')
		allcolleges     = all_colleges.objects.all().order_by('college_name')
		context['companies'] = allcompanies
		context['allcolleges'] = allcolleges
		try:
			context['form_errors'] = self.request.session['form_errors']
		except:
			pass



		return context

class writeReviewRest(TemplateView):
	template_name = "write_review_all.html"

	@method_decorator(login_required)
	def dispatch(self, request, *args, **kwargs):
		return super(self.__class__, self).dispatch(request, *args, **kwargs)


	def get_context_data(self, **kwargs):
		context = super(self.__class__, self).get_context_data(**kwargs)
		# GET USER PROFILE DATA
		if self.request.user.is_authenticated:
			if self.request.user.is_superuser:pass
			else:
				socialProvider = self.request.user.social_auth.get().provider
				if socialProvider == 'linkedin-oauth2':
					userUpdatedInsta = userinformation.objects.get(user=self.request.user)
					context['linkedin_profile_url'] = userUpdatedInsta.alternateUserprofileurl
				if socialProvider  == 'google-oauth2':
					userUpdatedInsta = userinformation.objects.get(user=self.request.user)
					context['linkedin_profile_url'] = userUpdatedInsta.alternateUserprofileurl
		context['allSocialLinks'] = socialMediaLinks.objects.all()

		compid          = self.kwargs['pk']
		interviewinsta      = company_interviews.objects.get(pk=compid)
		allQualifications       = qualifications.objects.all().order_by('qualification_name')


		context['interviewinsta'] =  interviewinsta
		context['allQualifications'] = allQualifications

		try:
			context['form_errors'] = self.request.session['form_errors']
		except:
			pass

		return context

class thanks_pageView(TemplateView):
	template_name = "thanks.html"


	def get_context_data(self, **kwargs):
		context = super(self.__class__, self).get_context_data(**kwargs)
		try:del self.request.session['form_errors']
		except:pass
		# GET USER PROFILE DATA
		if self.request.user.is_authenticated:
			if self.request.user.is_superuser:pass
			else:
				socialProvider = self.request.user.social_auth.get().provider
				if socialProvider == 'linkedin-oauth2':
					userUpdatedInsta = userinformation.objects.get(user=self.request.user)
					context['linkedin_profile_url'] = userUpdatedInsta.alternateUserprofileurl
				if socialProvider  == 'google-oauth2':
					userUpdatedInsta = userinformation.objects.get(user=self.request.user)
					context['linkedin_profile_url'] = userUpdatedInsta.alternateUserprofileurl

		context['allSocialLinks'] = socialMediaLinks.objects.all()

		return context

class companyView(TemplateView):
	template_name = "company_page.html"

	def get_context_data(self, **kwargs):
		context = super(self.__class__, self).get_context_data(**kwargs)
		try:del self.request.session['form_errors']
		except:pass
		# GET USER PROFILE DATA
		if self.request.user.is_authenticated:
			if self.request.user.is_superuser:pass
			else:
				socialProvider = self.request.user.social_auth.get().provider
				if socialProvider == 'linkedin-oauth2':
					userUpdatedInsta = userinformation.objects.get(user=self.request.user)
					context['linkedin_profile_url'] = userUpdatedInsta.alternateUserprofileurl
				if socialProvider  == 'google-oauth2':
					userUpdatedInsta = userinformation.objects.get(user=self.request.user)
					context['linkedin_profile_url'] = userUpdatedInsta.alternateUserprofileurl
		context['allSocialLinks'] = socialMediaLinks.objects.all()

		compid          = self.kwargs['pk']
		cominsta        = companies.objects.get(pk=compid)


		queryObject  = Q(company=cominsta) & Q(show_stat='show')
		allinterview = company_interviews.objects.filter(queryObject).order_by('-id')

		totalCount   = company_interviews.objects.filter(queryObject).count()

		paginator = Paginator(allinterview, 10)

		page = self.request.GET.get('page')
		try:
			allinterview = paginator.page(page)
		except PageNotAnInteger:
			allinterview = paginator.page(1)
		except EmptyPage:
			allinterview = paginator.page(paginator.num_pages)

		companySpoof = allinterview

		interviewcontent = []
		for inter in allinterview:
			user_status =  inter.submittedBy.is_superuser

			if user_status == True:
				profile_image = ""
			else:
				user_auth_type = inter.submittedBy.social_auth.get().provider
				if user_auth_type == 'linkedin-oauth2':
					userinfodeep  = userinformation.objects.get(user=inter.submittedBy)
					profile_image = userinfodeep.alternateUserprofileurl
				elif user_auth_type == 'google-oauth2':
					userinfodeep = userinformation.objects.get(user=inter.submittedBy)
					profile_image = userinfodeep.alternateUserprofileurl
				else:
					profile_image = "https://graph.facebook.com/{0}/picture?type=normal".format(inter.submittedBy.social_auth.get().uid)
			try:
				userSubinfo     = userinformation.objects.get(user=inter.submittedBy)
			except:
				userSubinfo = {
					"userProfileImage":"",
					"current_job_profile":"",
					"current_location":"",
				}
			mydict = {
				"main_data":inter,
				"user":userSubinfo,
				"profile_image":profile_image,
			}
			interviewcontent.append(mydict)
		context['company'] = cominsta
		context['allinterview'] = interviewcontent

dashboard/templates/allcompanies.html
{% extends "base_new.html" %}
{% load staticfiles %}
	{% block extra_css %}

      <link rel="stylesheet" href="{% static 'config/css/master_3columns.css' %}">
      <link rel="stylesheet" href="{% static 'config/css/contribute_form.css' %}">


    <style>
         .interview-show{
         display: none;
         }
         .interview-hide {
         display: none;
         }
         .review-info{
         display: none;
         }
         .disabled-select{
         color:rgba(214, 213, 213, 0.88);
         background-color:rgba(165, 162, 162, 0.19);
         }
      </style>
      <style>
      </style>

	{% endblock extra_css %}

{% block content %}



      <style>
         .layer{
         background: -webkit-linear-gradient(left, #191f30, #3d4972);
         background-color: #2B3451;
         }
      </style>



<div class="head-cover js-menu-shift">
	<div class="layer">

<h1 class="h1">Companies Search with "{{query}}"</h1>
		<div class="search-company">
			<form id="searchCompanyForm" action="" method="get">

				<input type="text" id="searchCompany"class="typeahead" name="q" placeholder="Type the name of the company you want to prepare for" value="{{query}}"  required="true">
				<button type="submit" value="" ><i class="icon-right-arrow"></i></button>
			</form>
		</div>
	</div>
</div>

      <section class="container-content">
         <section class="content__center">

              <section class="companies-block">


                                {% if result_count == 0 %}
                                        <div align="center">
                                                <h2>No Result Found :(</h2>

                                        </div>

                                {% endif %}


                                {% for comp in companies %}
                                        <a href="{% url 'dashboard:company' comp.id %}">
                                        <div class="company-tile">
                                            <h3>{{comp.company_name}}</h3>
                                            <div class="company-tile__details">
                                                <div class="company-tile__details__text">
                                                    <span>{{comp.state}}</span>
                                                    <span>{{comp.category}}</span>

                                                </div>
                                                <div class="company-tile__details__image">
                                                    <img src="/mediadump/{{comp.comapny_logo}}" alt="">
                                                </div>


                                            </div>
                                            <div class="btn accent" style="width:79%;color:white;text-align:center"> View Company</div>

                                        </div>
                                            </a>
                                {% endfor %}







                </section>


         </section>
         <section class="content__left">
            <!-- js-auto-position class should be added for fixing this on scroll -->
            <div class="content"></div>
         </section>
         <section class="content__right">
            <!-- js-auto-position class should be added for fixing this on scroll -->
            <div class="content"></div>
         </section>
      </section>










{% endblock content %}

dashboard/templates/image_profile.html
{% extends "base_new.html" %}
{% load staticfiles %}
	{% block extra_css %}

      <link rel="stylesheet" href="{% static 'config/css/master_3columns.css' %}">
      <link rel="stylesheet" href="{% static 'config/css/contribute_form.css' %}">


    <style>
         .interview-show{
         display: none;
         }
         .interview-hide {
         display: none;
         }
         .review-info{
         display: none;
         }
         .disabled-select{
         color:rgba(214, 213, 213, 0.88);
         background-color:rgba(165, 162, 162, 0.19);
         }
      </style>
      <style>
      </style>

	{% endblock extra_css %}

{% block content %}



      <section class="cover-image js-menu-shift">
         <div class="layer">
            <h1 class="h1">Update your profile Image</h1>
         </div>
      </section>
      <style>
         .layer{
         background: -webkit-linear-gradient(left, #191f30, #3d4972);
         background-color: #2B3451;
         }
      </style>



      <section class="container-content">
         <section class="content__center">
            <div class="content">
               <section class="main-content card floating-card">
                  <div class="top-block">

                  </div>
                  <div class=" ">
                     <form method="post"  action="{% url 'dashboard:update_user_profile' %}" id="ContributeIntroForm" name="ContributeIntroForm">
                         {% csrf_token %}



                                                    <div class="input-group">
														<label for="jobprofile" class="section-heading interview-hide">Your job profile</label>
														<input type="text" name="jobprofile" id="jobprofile" placeholder="Your job profile" required value="{{userinfo.current_job_profile}}" maxlength="150">
													</div>
                                                     <div class="input-group">
														<label for="location" class="section-heading interview-hide">Your Current Location</label>
													<input type="text" name="location" id="location" placeholder="Current location" required value="{{userinfo.current_location}}" maxlength="150">
													</div>
                                                    <div class="input-group">

													    <button class="btn" name="update">Update <i class="icon-right-arrow"></i></button>



                                                    </div>


                     </form>
                  </div>
               </section>


            </div>
         </section>
         <section class="content__left">
            <!-- js-auto-position class should be added for fixing this on scroll -->
            <div class="content"></div>
         </section>
         <section class="content__right">
            <!-- js-auto-position class should be added for fixing this on scroll -->
            <div class="content"></div>
         </section>
      </section>




{% endblock content %}

dashboard/templates/index.html
{% extends "base_new.html" %}


{% block content %}




<div class="head-cover js-menu-shift">
	<div class="layer">

		<h1>interview questions, experiences & tips</h1>
		<hr/>
		<h2 >your <span>secret</span> interview cheatsheet!</h2>
		<div class="search-company">
			<form id="searchCompanyForm" action="{% url 'dashboard:all_list_companies' %}" method="get">

				<input type="text" id="searchCompany"class="typeahead" name="q" placeholder="Type the name of the company you want to prepare for" required="true">
				<button type="submit" value="" ><i class="icon-right-arrow"></i></button>
			</form>
		</div>
	</div>
</div>

<h2 class="sector-group-title"><span>-------</span> Top companies interview questions <span>-------</span></h2>
<section class="companies-block">


		{% for comp in companies %}
	<a href="{% url 'dashboard:company' comp.co.id %}" title="{{comp.co.company_name}}">
		<div class="company-tile">
			<h3>{{comp.co.company_name}}</h3>
			<div class="company-tile__details">
				<div class="company-tile__details__text">
					<span>{{comp.count}} Interviews</span>
					<span>{{comp.co.startedDate}}</span>
					<span>{{comp.co.state}}</span>
					<span>{{comp.co.category}}</span>
				</div>
				<div class="company-tile__details__image">
					<img src="/mediadump/{{comp.co.comapny_logo}}" alt="{{comp.co.company_name}}">
				</div>
			</div>
		</div>
	</a>
	{% endfor %}
	<div align="center">
	    <div class="pagination_wrap_new ">



                                     {% if companySpoof.has_previous %}
                                                   <a href="?page={{ companySpoof.previous_page_number }}" class="pagination_text"><span class="icon-right-arrow icon-180-rotate"></span> Previous</a>
                                              {% endif %}

                                            <a>{{ companySpoof.number }} of {{ companySpoof.paginator.num_pages }}</a>
                                             {% if companySpoof.has_next %}

                           <a href="?page={{ companySpoof.next_page_number }}" class="pagination_text" style="margin-left: 1rem">Next
                             <span class="icon-right-arrow" style="display: inline-block;vertical-align: middle;position: relative;top: -1px;"></span>
                         </a>
                                                {% endif %}
                     </div>
		</div>




</section>
{% endblock content %}

dashboard/templates/login.html
{% extends "base_new.html" %}
{% load staticfiles %}
	{% block extra_css %}

      <link rel="stylesheet" href="{% static 'config/css/master_3columns.css' %}">
      <link rel="stylesheet" href="{% static 'config/css/contribute_form.css' %}">


    <style>
         .interview-show{
         display: none;
         }
         .interview-hide {
         display: none;
         }
         .review-info{
         display: none;
         }
         .disabled-select{
         color:rgba(214, 213, 213, 0.88);
         background-color:rgba(165, 162, 162, 0.19);
         }
      </style>
      <style>
      </style>

	{% endblock extra_css %}

{% block content %}



      <section class="cover-image js-menu-shift">
         <div class="layer">
            <h1 class="h1">Login Here</h1>
         </div>
      </section>
      <style>
         .layer{
         background: -webkit-linear-gradient(left, #191f30, #3d4972);
         background-color: #2B3451;
         }
      </style>



      <section class="container-content">
         <section class="content__center">
            <div class="content">
               <section class="main-content card floating-card">
                  <div class="top-block">

                  </div>
                  <div class="content__center">

                    <div align="center">
                                <a href="{% url 'social:begin' 'facebook' %}">
                                    <img  src="{% static 'config/image/facebook.png' %}"/></a>
                           <a href="{% url 'social:begin' 'google-oauth2' %}"> <img src="{% static 'config/image/googl.png' %}"/></a>

                           <a href="{% url 'social:begin' 'linkedin-oauth2' %}"> <img src="{% static 'config/image/linkedin.png' %}"/></a>
                    </div>





                  </div>
               </section>


            </div>
         </section>
         <section class="content__left">
            <!-- js-auto-position class should be added for fixing this on scroll -->
            <div class="content"></div>
         </section>
         <section class="content__right">
            <!-- js-auto-position class should be added for fixing this on scroll -->
            <div class="content"></div>
         </section>
      </section>




{% endblock content %}

dashboard/templates/profile.html
{% extends "base_new.html" %}
{% load staticfiles %}
	{% block extra_css %}

      <link rel="stylesheet" href="{% static 'config/css/master_3columns.css' %}">
      <link rel="stylesheet" href="{% static 'config/css/contribute_form.css' %}">


    <style>
         .interview-show{
         display: none;
         }
         .interview-hide {
         display: none;
         }
         .review-info{
         display: none;
         }
         .disabled-select{
         color:rgba(214, 213, 213, 0.88);
         background-color:rgba(165, 162, 162, 0.19);
         }
      </style>
      <style>
      </style>

	{% endblock extra_css %}

{% block content %}



      <section class="cover-image js-menu-shift">
         <div class="layer">
            <h1 class="h1">Update your profile information</h1>
         </div>
      </section>
      <style>
         .layer{
         background: -webkit-linear-gradient(left, #191f30, #3d4972);
         background-color: #2B3451;
         }
      </style>



      <section class="container-content">
         <section class="content__center">
            <div class="content">
               <section class="main-content card floating-card">
                  <div class="top-block">

                  </div>
                  <div class=" ">
                     <form method="post"  action="{% url 'dashboard:update_user_profile' %}" id="ContributeIntroForm" name="ContributeIntroForm">
                         {% csrf_token %}



                                                    <div class="input-group">
														<label for="jobprofile" class="section-heading interview-hide">Your job profile</label>
														<input type="text" name="jobprofile" id="jobprofile" placeholder="Your job profile" required value="{{userinfo.current_job_profile}}" maxlength="150">
													</div>
                                                     <div class="input-group">
														<label for="location" class="section-heading interview-hide">Your Current Location</label>
													<input type="text" name="location" id="location" placeholder="Current location" required value="{{userinfo.current_location}}" maxlength="150">
													</div>
                                                    <div class="input-group">

													    <button class="btn" name="update">Update <i class="icon-right-arrow"></i></button>



                                                    </div>


                     </form>
                  </div>
               </section>


            </div>
         </section>
         <section class="content__left">
            <!-- js-auto-position class should be added for fixing this on scroll -->
            <div class="content"></div>
         </section>
         <section class="content__right">
            <!-- js-auto-position class should be added for fixing this on scroll -->
            <div class="content"></div>
         </section>
      </section>




{% endblock content %}

dashboard/templates/register.html
{% extends "base_new.html" %}
{% load staticfiles %}
	{% block extra_css %}

      <link rel="stylesheet" href="{% static 'config/css/master_3columns.css' %}">
      <link rel="stylesheet" href="{% static 'config/css/contribute_form.css' %}">


    <style>
         .interview-show{
         display: none;
         }
         .interview-hide {
         display: none;
         }
         .review-info{
         display: none;
         }
         .disabled-select{
         color:rgba(214, 213, 213, 0.88);
         background-color:rgba(165, 162, 162, 0.19);
         }
      </style>
      <style>
      </style>

	{% endblock extra_css %}

{% block content %}



      <section class="cover-image js-menu-shift">
         <div class="layer">
            <h1 class="h1">Signup and share your interivew experiences here</h1>
         </div>
      </section>
      <style>
         .layer{
         background: -webkit-linear-gradient(left, #191f30, #3d4972);
         background-color: #2B3451;
         }
      </style>



      <section class="container-content">
         <section class="content__center">
            <div class="content">
               <section class="main-content card floating-card">
                  <div class="top-block">

                  </div>
                  <div class=" ">
                     <form method="post"  action="{% url 'dashboard:register_me' %}" id="ContributeIntroForm" name="ContributeIntroForm">
                         {% csrf_token %}



                                                    <div class="input-group">
														<label for="first_name" class="section-heading interview-hide">Enter your first name</label>
														<input type="text" name="first_name" id="first_name" placeholder="Enter your firstname" required value="" maxlength="150">
													</div>
                                                     <div class="input-group">
														<label for="last_name" class="section-heading interview-hide">Enter your last name</label>
														<input type="text" name="last_name" id="last_name" placeholder="Enter your lastname" required value="" maxlength="150">
													</div>
                                                        <div class="input-group">
														<label for="email" class="section-heading interview-hide">Enter your email</label>
													<input type="email" name="email" id="email" placeholder="Password" required value="" maxlength="150">
													</div>
                                                     <div class="input-group">
														<label for="k" class="section-heading interview-hide">Enter your password</label>
													<input type="password" name="password" id="k" placeholder="Password" required value="" maxlength="150">
													</div>
                                                    <div class="input-group">

													    <button class="btn accent" name="register">Register Me <i class="icon-right-arrow"></i></button>

                                                        <a class="btn" href="{% url 'dashboard:login' %}">Login</a>
                                                         {% if msg %}
                                                            <font color="red">{{msg}}</font>
                                                        {% endif %}

                                                    </div>


                     </form>
                  </div>
               </section>


            </div>
         </section>
         <section class="content__left">
            <!-- js-auto-position class should be added for fixing this on scroll -->
            <div class="content"></div>
         </section>
         <section class="content__right">
            <!-- js-auto-position class should be added for fixing this on scroll -->
            <div class="content"></div>
         </section>
      </section>




{% endblock content %}